export const imgList = {
  backAction: require('resources/backAction.png'),
  nextAction: require('resources/nextAction.png'),
  logo: require('resources/logo.png'),
  logoText: require('resources/logo_text.png'),
  searchIcon: require('resources/local_search_icon.svg'),
  defaultUser: require('resources/default_user.png'),
  commentNormal: require('resources/bv_comment.svg'),
  skin: require('resources/tv_skin.svg'),
  setting: require('resources/tv_setting.svg'),
  toMini: require('resources/tv_to_mini.svg'),
  leftArrow: require('resources/left.svg'),
  listen: require('resources/listen.svg'),
  play: require('resources/play.svg'),
  pause: require('resources/pause.svg'),
}
